# Generated by Django 4.0.6 on 2022-07-30 18:34

import ckeditor.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTemplates',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('subject', models.CharField(max_length=255, verbose_name='subject')),
                ('content', ckeditor.fields.RichTextField(help_text='в шаблоне можно использовать переменные {{name}} - имя и {{content}} - содержание уведомления', verbose_name='content')),
                ('channel', models.TextField(choices=[('email', 'email'), ('sms', 'sms')], max_length=8, verbose_name='channel')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Template',
                'verbose_name_plural': 'Templates',
            },
        ),
    ]
